# Generated by Django 4.1.7 on 2023-03-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('dateofbirth', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField(unique=True)),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contact_table',
            },
        ),
    ]
