# Generated by Django 4.1.7 on 2023-03-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_contact_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Home', 'Home'), ('Jewelry', 'Jewelry'), ('Electronics', 'Electronics'), ('Clothes', 'Clothers'), ('Others', 'Others')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='productimages')),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
    ]
