# Generated by Django 4.1.7 on 2023-03-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
